---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    
  roles:
    - deploy_app

    # 7.6.1810 ansible -m setup localhost | grep distribution_version