---
- name: hello 
  shell:  sudo systemctl status ssh
  register: os_data


- name: print 
  debug:
    var: os_data


- name: Install httpd and php

  apt:
    name:
      - apache2
      - php
      - php-mysql
    state: absent